name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa
          pip install --timeout=300 -r requirements.txt

      - name: Build with Nuitka
        run: |
          python3 -c "import sys; sys.path.append('./app/common'); import config; print(config.VERSION)" > version.txt
          version=$(sed -n '4p' version.txt)
          echo "VERSION=${version}" >> "$GITHUB_ENV"
          rm -rf version.txt
          python deploy.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-Downloader-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}
          path: dist/Ghost-Downloader-3.dist
